version: 2
jobs:
  build:
    docker:
      -
        image: 'circleci/node:8.9.4'
    working_directory: ~/expressCartNode
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      -
        run: 'npm install'
      -
        save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
  test-unit:
    docker:
      -
        image: 'circleci/node:8.9.4'
    working_directory: ~/expressCartNode
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      -
        run: 'npm install'
  test-e2e:
    docker:
      -
        image: 'circleci/node:8.9.4'
    working_directory: ~/expressCartNode
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      -
        run: 'npm install'
  test-coverage:
    docker:
      -
        image: 'circleci/node:8.9.4'
    working_directory: ~/expressCartNode
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      -
        run: 'npm install'
  deploy-develop:
    docker:
      -
        image: 'circleci/node:8.9.4'
    working_directory: ~/expressCartNode
    steps:
      - checkout
      -
        command: # shell command
  deploy-master:
    docker:
      -
        image: 'circleci/node:8.9.4'
    working_directory: ~/expressCartNode
    steps:
      - checkout
      -
        command: #shell command
workflows:
  version: 2
  build-and-deploy-on-hold:
    jobs:
      -
        build:
          filters:
            branches:
              only:
                - master
                - develop
      -
        test-all:
          requires:
            - build
      -
        hold:
          type: approval
          requires:
            - test-all
      -
        deploy-develop:
          requires:
            - build
            - test-all
            - hold
          filters:
            branches:
              only: develop
      -
        deploy-master:
          requires:
            - build
            - test-all
            - hold
          filters:
            branches:
              only: master
