version: 2

jobs:
  build:
    docker:

      - image: 'circleci/node:8.9.4'
      - image: 'circleci/mongo:3.4.10'
        environment:
          - MONGO_HOST: '127.0.0.1:27017'
          - MONGODB_DB: expresscart
    working_directory: ~/expressCartNode
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
  test:
    docker:
      - image: 'circleci/node:8.9.4'
      - image: 'circleci/mongo:3.4.10'
    environment:
      - MONGO_HOST: '127.0.0.1:27017'
      - MONGODB_DB: expresscart
    working_directory: ~/expressCartNode
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: npm run test
  deploy-qa:
    docker:
      - image: 'circleci/node:8.9.4'
      - image: 'circleci/mongo:3.4.10'
    working_directory: ~/expressCartNode
    steps:
      - checkout
      - command: null
  deploy-master:
    docker:
      - image: 'circleci/node:8.9.4'
    working_directory: ~/expressCartNode
    steps:
      - checkout
      - command: null
workflows:
  version: 2
  build-and-deploy-on-hold:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - qa
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy-qa:
          requires:
            - test
            - build
            - hold
          filters:
            branches:
              only: qa
      - deploy-master:
          requires:
            - build
            - test
            - hold
          filters:
            branches:
              only: master
